on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
name: pull_request
jobs:
  linting_and_formatting:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.10"
          architecture: "x64"
      - run: pip install poetry
      - run: poetry install
      - run: make run-ci
  python_unit_test:
    name: Python Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.10"
          architecture: "x64"
      - run: pip install poetry
      - run: poetry install
      - run: make run-pytest
